on:
    push:
        branches:
            - '*'
            - '!*/*'
        tags:
          - 'never-on-tags'
        paths:
          - 'ubuntu-python36.Dockerfile'
          - '.github/workflows/ubuntu-python36.yml'

name: ubuntu-python
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GPR
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p $GH_TOKEN
        env:
          GH_TOKEN: ${{ secret.GITHUB_TOKEN }}
      - run: |
          docker build . --tag build -f ubuntu-python36.Dockerfile
      - run: |
          image=docker.pkg.github.com/judge2020/dockerfiles/ubuntu-python36
          docker tag panda3d:latest $image:${GITHUB_SHA:0:20}
          docker tag panda3d:latest $image:$(date +%s)
          docker tag panda3d:latest $image:latest
          docker push $image
